# Dockerfile - container simples com Python
FROM python:3.11-slim

# Diretório de trabalho
WORKDIR /app

# Copia o código-fonte e o requirements
COPY ./src /app/src
COPY requirements.txt .

# Define o PYTHONPATH
ENV PYTHONPATH=/app/src

# Instala as dependências
RUN pip install --no-cache-dir -r requirements.txt

# Comando que inicia o client MQTT
CMD ["python", "src/mottu/mqtt/client.py"]
